// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiAu9F6YmklEvXAvOK2NT_cjBLclhVCwc',
    appId: '1:504053698707:web:bf9427c0569b719b33fd66',
    messagingSenderId: '504053698707',
    projectId: 'scholar-match-fyp',
    authDomain: 'scholar-match-fyp.firebaseapp.com',
    storageBucket: 'scholar-match-fyp.firebasestorage.app',
    measurementId: 'G-TNHQFBSWDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKL_gAFLybzrFxqgGTYLDmpjIYCRa9YPg',
    appId: '1:504053698707:android:da641f75fecc7dd333fd66',
    messagingSenderId: '504053698707',
    projectId: 'scholar-match-fyp',
    storageBucket: 'scholar-match-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcihX93yxtt5sYUZcM81HNtwoRywhqu0',
    appId: '1:504053698707:ios:5c19c195e9cf13b033fd66',
    messagingSenderId: '504053698707',
    projectId: 'scholar-match-fyp',
    storageBucket: 'scholar-match-fyp.firebasestorage.app',
    iosBundleId: 'com.example.scholarMatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcihX93yxtt5sYUZcM81HNtwoRywhqu0',
    appId: '1:504053698707:ios:5c19c195e9cf13b033fd66',
    messagingSenderId: '504053698707',
    projectId: 'scholar-match-fyp',
    storageBucket: 'scholar-match-fyp.firebasestorage.app',
    iosBundleId: 'com.example.scholarMatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiAu9F6YmklEvXAvOK2NT_cjBLclhVCwc',
    appId: '1:504053698707:web:de06de8204ee402c33fd66',
    messagingSenderId: '504053698707',
    projectId: 'scholar-match-fyp',
    authDomain: 'scholar-match-fyp.firebaseapp.com',
    storageBucket: 'scholar-match-fyp.firebasestorage.app',
    measurementId: 'G-DNQE2T97T7',
  );
}
